<?php
/*
FOR LIVE TRANSACTIONS - LIVE
FOR TEST TRANSACTIONS - TEST
MID - CHECK YOUR DASHBOARD FOR MID
MID KEY - CHECK YOUR DASHBOARD FOR MID KEY
*/
define ('KP_ENVIRONMENT', 'LIVE'); //CHANGE HERE WHICH TYPE OF TXN YOU DONE.
define('KPMID', 'YOUR_MID_KEY');//CHANGE THIS MID RECEIVED FROM KWIKPAISA.
define('KPMIDKEY', 'YOUR_MID_SALT_KEY');//CHANGE MIDKEY RECEIVED FROM KWIKPAISA.
define('TXN_CURRENCY', 'INR');//CHANGE TXN_CURRENCY AS TXN_CURRENCY NEEDED, DEFAULT IS INR.
//YOU MAY CHANGE THIS CURRENCY IN ISO FORMAT MENTIONED INTO WEBSITE
$KP_STATUS_QUERY_URL='https://pispp.kwikpaisa.com/CheckOut/Status';
$KP_TXN_URL='https://pispp.kwikpaisa.com/CheckOut/TxnProcess';
$CALLBACK_URL='YOUR_RETURN_URL';
define('KP_REFUND_URL', '');
define('KP_STATUS_QUERY_URL', $KP_STATUS_QUERY_URL);
define('KP_TXN_URL', $KP_TXN_URL);
define('CALLBACK_URL', $CALLBACK_URL);
?>
